[workspace]
resolver = "2"
members = [
    "app",
    "bootloader",
]

[profile.dev]
debug = 2
debug-assertions = true
opt-level = 2
overflow-checks = true

[profile.release]
debug = 2
debug-assertions = false
lto = 'fat'
opt-level = 2
overflow-checks = false

# do not optimize proc-macro crates = faster builds from scratch
[profile.dev.build-override]
debug = false
debug-assertions = false
overflow-checks = false
opt-level = 0

[profile.release.build-override]
debug = false
debug-assertions = false
overflow-checks = false
opt-level = 0

[profile.test]
debug = 2
debug-assertions = true
opt-level = 2
overflow-checks = true

[profile.bench]
debug = 2
debug-assertions = false
lto = 'fat'
opt-level = 3

# for each crate in the `tests` directory
[[test]]
name = "probe"  # tests/probe.rs
harness = false
